apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-cluster
  region: us-east-1
  version: "1.30"

iam:
  # Force eksctl to use the existing AWS Academy LabRole
  serviceRoleARN: arn:aws:iam::601891175772:role/LabRole
  withOIDC: true

vpc:
  cidr: 192.168.0.0/16

managedNodeGroups:
  - name: linux-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3

    # Use the same LabRole for worker nodes
    iam:
      instanceRoleARN: arn:aws:iam::601891175772:role/LabRole

