apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-cluster
  region: us-east-1

managedNodeGroups:
  - name: linux-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      instanceRoleARN: arn:aws:iam::601891175772:role/c177358a4583888l12591104t1w601891175-LabEksNodeRole-XWfrb01iq8XC

